# Deep Learning for Natural Language Processing
## Exercise Sheet 4 - numpy

You should answer each question with a line of code in the cell below.
A correctly completed answer gives 2 points. Partially correct answers give 1 point.
For each of these tasks, there is a way to solve it directly and elegantly with numpy, we will therefor not accept solutions with for-loops, long lists of typed out array indices and similar constructions.

**Submission deadline:** 23.11.2021, 23:59 

**Exercise:** 01.12.2021

**Instructions for submission:** 
You should complete the parts of the exercises that are marked as **TODO**. A correctly completed **TODO** gives 2 bonus points. Partially correct answers give 1 bonus point. After completing the exercise, save a copy of the notebook as exercise4_numpy_MATRIKELNUMMER.ipynb, where MATRIKELNUMMER is your matriculation number. Then upload the notebook to moodle (submission exercise sheet 4).

**Note:** In order to understand the code, it can be helpful to experiment a bit during development. You are welcome to print variables, reduce dataset sizes, or experiment with hyperparameters. But please remove these changes before submitting the notebook. If we cannot run your notebook (e.g., because you commented out an important variable, or because a print statement is congesting stdout), then we cannot grade it. 

Total points: 30

* import the numpy package under the name np

In [3]:
#TODO
import numpy as np

* generate a vector with values ranging from 42 inclusive to 80 exclusive

In [4]:
#TODO
vector1 = np.array([a for a in range(42,80)])

[42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65
 66 67 68 69 70 71 72 73 74 75 76 77 78 79]


* revert the previously generated vector

In [6]:
#TODO
vector1 = np.flip(vector1)
print(vector1)

[79 78 77 76 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56
 55 54 53 52 51 50 49 48 47 46 45 44 43 42]


* create a null vector of size 15 but the third, fifth and eight values set to 1

In [8]:
#TODO
vector2 = np.empty(15)
vector2[2] = vector2[4] = vector2[7] = 1
print(vector2)

[1.7165319e-316 0.0000000e+000 1.0000000e+000 0.0000000e+000
 1.0000000e+000 0.0000000e+000 0.0000000e+000 1.0000000e+000
 0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000
 0.0000000e+000 0.0000000e+000 0.0000000e+000]


* create a 4x4 matrix with random values

In [16]:
#TODO
matrix1 = np.random.rand(4, 4)
print(matrix1)

[[0.57982976 0.58067732 0.41824408 0.54315018]
 [0.71615977 0.06102696 0.01251527 0.11611251]
 [0.93599878 0.75567186 0.10112035 0.93950186]
 [0.59803789 0.50466145 0.66197514 0.72677184]]


* create a 5x5 2d array with 0 on the borders and 1 inside

In [15]:
#TODO
array1 = np.ones((5,5))
array1[1:-1,1:-1] = 0
print(array1)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


* create a 4x5 2d array with random values and compute the mean values of each row

In [17]:
#TODO
array2 = np.random.randn(4,5)
for a in array2:
    print(np.mean(a))

0.6527741172912768
0.4780594717969108
0.49322780192797044
0.7642434134481009


* create a vector of size 5 with values drawn from an uniform distribution and sort it

In [23]:
#TODO
vector3 = np.random.uniform(0.0, 1.0, 5)
print("Before: ", vector3)
vector3 = np.sort(vector3)
print("After: ", vector3)

Before:  [0.07040179 0.28390012 0.79524985 0.5665684  0.30377521]
After:  [0.07040179 0.28390012 0.30377521 0.5665684  0.79524985]


* consider an array of shape (3,4,5), what is the index (x,y,z) of the 30th element? Note that
there is a way to find this index directly within numpy

In [24]:
#TODO
array3 = np.random.randn(3,4,5)
# to find nth element, which n will follow the equation n = x*y*z, and x<=y<=z
# In this kind of situation, we set n = 30
n=30
# Finding the index
x = y = z = 0
for a in range(3):
    for b in range(4):
        for c in range(5):
            if a*b*c == n:
                x = a
                y = b
                z = c
                break
print(array3[x][y][z])

-0.10476269907275165


* compute the dot product of a 3x4 and a 4x2 matrix, each containing only ones

In [26]:
#TODO
# Generate two random arrays as an example
array4 = np.ones((3, 4))
array5 = np.ones((4, 2))
result1 = np.dot(array4, array5)
print(result1)

[[4. 4.]
 [4. 4.]
 [4. 4.]]


* create an array containing all dates of the days you had at your disposal to work on this sheet including start and
end day in the format YYYY-MM-DD. Hint: there is a special data type for dates in numpy. Do not simply type all individual days out.

In [39]:
#TODO
array6 = np.arange('2021-11-17', '2021-11-23', dtype='datetime64[D]')

* create a 1d array with 10 random values between 0 and 5 and find the value nearest to 4

In [37]:
#TODO
list1 = []
for a in range(10):
    list1.append(np.random.randint(0,5))
array7 = np.array(list1)
nearest_value = array7[(np.abs(array7-4)).argmin()]
print(nearest_value)

4


* Create a four-dimensional array and compute the sums over the first two axes at once

In [50]:
#TODO
array8 = np.random.randn(1,2,3,4)
sum1 = np.sum(array8,axis=2)
print(np.sum(sum1))

7.992066819429298


* given the array [0,1,2,3,4,5,0,2,3,1,2,3,2,3,2], find the most frequent value and its indexes

In [53]:
x = [0,1,2,3,4,5,0,2,3,1,2,3,2,3,2]
x_arr = np.array(x)
mfn = np.bincount(x_arr).argmax()
mfn_index = 0
for a in range(len(x)):
    if a is mfn:
        mfn_index = a
        break
print(mfn)
print(mfn_index)
#TODO

2
0


* given the array [0,0,1,5,0,2,0,0,3,0], find all indexes of non-zero values and all indexes of values
greater than 1

In [54]:
x = [0,0,1,5,0,2,0,0,3,0]
index2 = []
index3 = []
for a in x:
    if a != 0:
        index2.append(a)
    if a > 1:
        index3.append(a)
print(index2)
print(index3)

#TODO

[1, 5, 2, 3]
[5, 2, 3]
